### ISSUE TITLE
typo in extconf preventing install?

### ISSUE THREAD

**Issue by simon-dedeo** [yoshoku/numo-blis#2]
Thank you for writing this! There may be a very simple typo preventing the full install of numo-blis? (I'm using 10.12/macOS sierra)

`... sudo gem2.5 install numo-blis
Building native extensions. This could take a while...
ERROR:  Error installing numo-blis:
	ERROR: Failed to build gem native extension.

    current directory: /opt/local/lib/ruby2.5/gems/2.5.0/gems/numo-blis-0.2.0/ext/numo/blis
/opt/local/bin/ruby2.5 -r ./siteconf20220117-81554-1atkjot.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/local/bin/$(RUBY_BASE_NAME)2.5
	--enable-threading
extconf.rb:37:in `<main>': undefined method `try_complie' for main:Object (NoMethodError)
Did you mean?  try_compile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/local/lib/ruby2.5/gems/2.5.0/extensions/x86_64-darwin-16/2.5.0/numo-blis-0.2.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/local/lib/ruby2.5/gems/2.5.0/gems/numo-blis-0.2.0 for inspection.
Results logged to /opt/local/lib/ruby2.5/gems/2.5.0/extensions/x86_64-darwin-16/2.5.0/numo-blis-0.2.0/gem_make.out
`

**Comment by yoshoku** [comment]
Maybe this issue has been fixed. Thank you for your report.
